---
- name: install and enable httpd
  tasks:
    - name: Ensure teh HTTPd package is installed
      yum:
        name: httpd
        state: present
      become: True
    - name: Ensure the HTTPd service is enabled and running
      service:
       name: httpd
       state: started
       enabled: True
      become: True
...