---
- hosts: web
  remote_user: ansible
  tasks:
  - name: Ensure EPEL is installed
    yum:
      name: epel-release
      state: present
    become: True
  - name: Ensure libselinux-python is present
    yum:
      name: libselinux-python
      state: present
    become: True 
  - name: Ensure libsemanage-python is present
    yum:
      name: libsemanage-python
      state: present
    become: True
  - name: Ensure latest rev is installed
    yum:
      name: "*"
      state: latest
    become: True
  - name: Ensure NTP is installed
    yum:
      name: ntp
      state: present
    become: True
  - name: Ensure timezone is set to Denver
    file:
      src: /usr/share/zoneinfo/MST
      dest: /etc/localtime
      state: link
      force: yes
    become: True
  - name: Ensure NTP service is installed and enabled
    service:
      name: ntpd
      state: started
      enabled: True
    become: True
  - name: Ensure FirewallD is present and enabled
    yum:
      name: firewalld
      state: present
    become: True
  - name: Ensure FirewallD is running
    service:
      name: firewalld
      state: started
      enabled: True
    become: True
  - name: Ensure FirewallD allows ssh access
    firewalld:
      service: ssh
      state: enabled
      permanent: True
      immediate: True
    become: True
  - name: Ensure MOTD file is present and updated
    template:
      src: motd
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644
    become: True
  - name: Ensure the hostname matches that of the inventory file
    hostname:
      name: "{{ inventory_hostname }}"
    become: True
...